version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always

  client:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mosquitto
    stdin_open: true
    tty: true
    entrypoint: ["python3", "/app/chat_client.py"]

  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mosquitto
    stdin_open: true
    tty: true
    entrypoint: ["python3", "/app/chat_server.py"]

volumes:
  mosquitto_data:
  mosquitto_log:
